### ISSUE TITLE
Problem with rewrite engine

### ISSUE THREAD

**Issue by labo-css** [iksi/Fingerprint#2]
Hello, i just tried your plugin and i have a little problem.
The code i used is this :

```
<!--  <?php echo css('assets/css/main.css') ?>-->
  <?php echo cssfingerprint('assets/css/main.css') ?>
```

And what i get :

```
<!--  <link rel="stylesheet" href="http://192.168.0.10/dev/pro/ad62/assets/css/main.css">-->
  <link rel="stylesheet" href="http://192.168.0.10/dev/pro/ad62/assets/css\main.7eb9c8dbba117ab1727e7ef47a65b3d5.css">
```

The "\" just before the main is a problem i think, what can i do?

Edit : it seems to work in production so it's a local problem. I use xammp, do you have an idea about this?

**Comment by labo-css** [comment]
Is it possible to made it work in localhost?

**Comment by iksi** [comment]
Could you check if my latest commit solved the issue? https://github.com/iksi/KirbyFingerprint/commit/bba6a033d8bfce7470f4e3e6af9db24a1b55b953

**Comment by labo-css** [comment]
The "\" problem is solved but... i got this : 
http://192.168.0.10/dev/pro/ad62/assets/css/main.7eb9c8dbba117ab1727e7ef47a65b3d5.css

The url is not supposed to is like css/file/path/style.css?numericid ?
I got a dot, not an interrogation point.

**Comment by iksi** [comment]
The file in the url is supposed to look like: `main.7eb9c8dbba117ab1727e7ef47a65b3d5.css`.

It’s not using a querystring like `main.css?7eb9c8dbba117ab1727e7ef47a65b3d5`. You can read more on that: http://www.stevesouders.com/blog/2008/08/23/revving-filenames-dont-use-querystring/.

If it doesn’t work, it probably has to do with the `.htaccess` file.

**Comment by labo-css** [comment]
The htaccess is the standard kirby htaccess + your code.

**Comment by iksi** [comment]
Could you show me the full `.htaccess`?

**Comment by labo-css** [comment]
Do i said i was dumb?
I am...

See :

```
# Kirby .htaccess

# rewrite rules
<IfModule mod_rewrite.c>

# enable awesome urls. i.e.:
# http://yourdomain.com/about-us/team
RewriteEngine on

#Fingerprint rewrite (uncomment if u use it)
#RewriteCond %{REQUEST_FILENAME} !-f
#RewriteRule ^(.+)\.([0-9a-z]{32})\.(js|css|png|jpe?g|gif|svg|ico)$ $1.$3 [L]

# make sure to set the RewriteBase correctly
# if you are running the site in a subfolder.
# Otherwise links or the entire site will break.
#
# If your homepage is http://yourdomain.com/mysite
# Set the RewriteBase to:
#
# RewriteBase /mysite

# block text files in the content folder from being accessed directly
RewriteRule ^content/(.*)\.(txt|md|mdown)$ error [R=301,L]

# block all files in the site folder from being accessed directly
RewriteRule ^site/(.*) error [R=301,L]

# block all files in the kirby folder from being accessed directly
RewriteRule ^kirby/(.*) error [R=301,L]

# make panel links work
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^panel/(.*) panel/index.php [L]

# make site links work
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*) index.php [L]

</IfModule>

# Additional recommended values
# Remove comments for those you want to use.
#
# AddDefaultCharset UTF-8
#
# php_flag short_open_tag on
```

I... forgot to uncomment when testing your last commit. My bad...
